language: node_js

os:
  - linux

node_js:
  - "7"
  - "6"

env:
  - KONG_VERSION=0.9
  - KONG_VERSION=0.10

services:
  - docker

before_install:
  - docker run -d --name kong-database -e "POSTGRES_USER=kong" -e "POSTGRES_DB=kong" postgres:9.4
  - sleep 5
  - docker run -d --name kong --link kong-database:kong-database -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=kong-database" -p 8001:8001 kong:$KONG_VERSION
  - sleep 5
  - curl 127.0.0.1:8001

install:
  - npm install
  - npm run build

